title: pramod Varma's Personal Blog
description: > # this means to ignore newlines until "baseurl:"
  Personal blog of Pramod Varma, Chief Architect of Aadhaar, India Stack, UPI, Becknprotocol and many other digital public infrasrtucture in India
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pramodkvarma.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Pramod Varma # add your name
author-img: druid-sketch.png # add your photo
about-author: Personal blog of Pramod Varma, Chief Architect of Aadhaar, India Stack, UPI, Becknprotocol and many other digital public infrasrtucture projects in India # add description
social-twitter: pramodkvarma # add your Twitter handle
#social-facebook: # add your Facebook handle
social-github: pramodkvarma # add your Github handle
social-linkedin: pramodkvarma # add your Linkedin handle
#social-email: # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
